title: 'Create Java project in Eclipse '
description: 'Create Java project in Eclipse '
template:
  repo: create-java-project-in-eclipse-template
  name: create-java-project-in-eclipse
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
